### ISSUE TITLE
FSharp / CSharp

### ISSUE THREAD

**Issue by ohlawdie** [CarlVerret/CycleThroughFiles#1]
Is this working? I'm afraid that I can't get an event to occur when I press my keybind(s) associated with CycleThroughFiles..thanks! I am within a project do I need to be in a 'folder view' or?

**Comment by CarlVerret** [comment]
yes it does, I use it everyday !

Actually i'm cycling through  .cshtml /  cshtml.cs  /  .ts files
![image](https://user-images.githubusercontent.com/25437410/109044120-083d1d80-76a0-11eb-8c7e-9d1e5c6c300e.png)

![image](https://user-images.githubusercontent.com/25437410/109044299-40dcf700-76a0-11eb-99ed-eae076fbf561.png)

I am binding F7 and Shift-F7 (reverse) cycle.  For convienence, I aslo nested .ts (typescript) file under cshtml

**Comment by CarlVerret** [comment]
I am using project view, but I just tested it with folder view and it works !

**Comment by CarlVerret** [comment]
Did you downloaded the ext  via vs-marketPlace ?
https://marketplace.visualstudio.com/items?itemName=CarlVerret.CycleThroughFiles-001

**Comment by ohlawdie** [comment]
Strange, just not working for me. Yes I downloaded from VS Marketplace. Is this for navigating a "nested" looking file like the one you've shown above with a code-behind and whatever or is it for navigating files within a folder/directory?

**Comment by CarlVerret** [comment]
it actually uses the siblings functionnality:

 var curntFile = Path.GetFileName( _dte.ActiveDocument.FullName);
 var curntPath = Path.GetDirectoryName(_dte.ActiveDocument.FullName);
 var siblings = DocumentHelpers.**Siblings**(_dte.ActiveDocument.FullName).ToArray();

**Comment by CarlVerret** [comment]
are your files sitting next to each other ?

**Comment by ohlawdie** [comment]
Ya the files are next to each other...hrmm I wonder if there is a way I can test with something like Visual Commander

**Comment by CarlVerret** [comment]
sorry to hear that did you try another key instead of F7 ?

**Comment by CarlVerret** [comment]
which version of VS are you using ?

**Comment by ohlawdie** [comment]
Let me try something I use an external program SharpKeys to rebind or remove the functionality of some of my fn media keys, F7 being an unbound key. CycleThroughFiles did not have a hotkey defined initially after my installation so I started with alt-c, then did ctrl+Shift+f, then f6. I will register and bind F7 as a key again and let you know what happens.

**Comment by ohlawdie** [comment]
No luck, I am using vs2019 and I reinstalled CycleThroughFiles!

**Comment by ohlawdie** [comment]
so I was actually using vs2019 preview - doesn't work - but works in vs2019

**Comment by CarlVerret** [comment]
that,s strange!  I've been using preview for many months now!

**Comment by ohlawdie** [comment]
Is there any possible way I can have it be so your extension only cycles / iterates through files of the same extension?

**Comment by ohlawdie** [comment]
it does work in VS2019 preview I was using it wrong prior to discovering that files of the same name literally means files of the same name lol

**Comment by CarlVerret** [comment]
you mean having 2 modes :  same name or same extension ?

**Comment by ohlawdie** [comment]
Only extensions would be nice! Preferably just one mode but two is a natural idea as well!

**Comment by CarlVerret** [comment]
maybe as a config toggle...

**Comment by CarlVerret** [comment]
I wonder what would be your typical use case for different files with same extension ? You'd like to cycle through closed files in the same dir ? Otherwise, I can't see much difference with traditionnal CTRL+TAB ?
